import { Pokemon, PokemonType } from "./types";

const data: Pokemon[] = [
    {
        hebrewName: "נגביר",
        englishName: "Negeveer",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/650-1.png",
        linkId: 87267,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "רודורן",
        englishName: "Rudorn",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/651-1.png",
        linkId: 87518,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "מיסטלופ",
        englishName: "Mistelope",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/652-1.png",
        linkId: 87519,
        majorWeaknesses: [PokemonType.Poison],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Flying, PokemonType.Metal],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Dragon, PokemonType.Dark, PokemonType.Science, PokemonType.Religion],
    }, {
        hebrewName: "קוהיט",
        englishName: "Kuheat",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/653.png",
        linkId: 87520,
        majorWeaknesses: [PokemonType.Rock],
        weaknesses: [PokemonType.Water, PokemonType.Electricity, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Bug, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "סטרלטון",
        englishName: "Streleton",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/654.png",
        linkId: 87521,
        majorWeaknesses: [PokemonType.Rock],
        weaknesses: [PokemonType.Water, PokemonType.Electricity, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Bug, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "ווספייר",
        englishName: "Vespyre",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/655.png",
        linkId: 87522,
        majorWeaknesses: [PokemonType.Earth],
        weaknesses: [PokemonType.Water, PokemonType.Fighting, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Normal, PokemonType.Grass, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Psychic, PokemonType.Bug, PokemonType.Dragon, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "סליאאון",
        englishName: "Slieon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/656.png",
        linkId: 87523,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Metal],
    }, {
        hebrewName: "מדיריסט",
        englishName: "Medirist",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/657.png",
        linkId: 87524,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Metal],
    }, {
        hebrewName: "רפידארד",
        englishName: "Rapidard",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/658.png",
        linkId: 87525,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Flying, PokemonType.Psychic, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Bug, PokemonType.Rock, PokemonType.Dark, PokemonType.Metal],
    }, {
        hebrewName: "גרסקט",
        englishName: "Grassect",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/659.png",
        linkId: 87526,
        majorWeaknesses: [PokemonType.Fire, PokemonType.Flying],
        weaknesses: [PokemonType.Ice, PokemonType.Poison, PokemonType.Bug, PokemonType.Rock],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "גרסיקדה",
        englishName: "Grassycada",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/660.png",
        linkId: 87527,
        majorWeaknesses: [PokemonType.Fire, PokemonType.Flying],
        weaknesses: [PokemonType.Ice, PokemonType.Poison, PokemonType.Bug, PokemonType.Rock],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "ציקדרסגון",
        englishName: "Cykadrassgon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/661.png",
        linkId: 87528,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Flying, PokemonType.Rock, PokemonType.Dragon, PokemonType.Fairy],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Culture],
    }, {
        hebrewName: "זיפ זיפ",
        englishName: "Zip zip",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/662.png",
        linkId: 87529,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Flying, PokemonType.Bug, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "זיפ זאפ",
        englishName: "Zip zap",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/663.png",
        linkId: 87530,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Flying, PokemonType.Bug, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "זאפ זאפ",
        englishName: "Zap zap",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/664.png",
        linkId: 87531,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Flying, PokemonType.Bug, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "סנופקור",
        englishName: "Snopekor",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/665.png",
        linkId: 87532,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Metal],
    }, {
        hebrewName: "סנוברייק",
        englishName: "Snowbreak",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/666.png",
        linkId: 87533,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Rock],
        resistancess: [PokemonType.Water, PokemonType.Ice],
    }, {
        hebrewName: "סטורייד",
        englishName: "Storaid",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/667.png",
        linkId: 87534,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Rock],
        resistancess: [PokemonType.Water, PokemonType.Ice],
    }, {
        hebrewName: "פירקון",
        englishName: "Fircoon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/668.png",
        linkId: 87535,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Fighting, PokemonType.Earth, PokemonType.Rock, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Ice, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Metal],
    }, {
        hebrewName: "לנוני",
        englishName: "Lanoni",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/669.png",
        linkId: 87536,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Poison, PokemonType.Metal],
        resistancess: [PokemonType.Bug, PokemonType.Ghost, PokemonType.Dragon, PokemonType.Dark, PokemonType.Science],
    }, {
        hebrewName: "טויפייפ",
        englishName: "Toipape",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/670.png",
        linkId: 87538,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
    }, {
        hebrewName: "טריגוופ",
        englishName: "Trigope",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/671.png",
        linkId: 87559,
        majorWeaknesses: [PokemonType.Bug, PokemonType.Dark, PokemonType.Religion],
        weaknesses: [PokemonType.Ghost, PokemonType.Dragon],
        resistancess: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Psychic, PokemonType.Science],
    }, {
        hebrewName: "ספייבלאו",
        englishName: "Spileblow",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/672.png",
        linkId: 87560,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Psychic, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Religion],
    }, {
        hebrewName: "ספייקלר",
        englishName: "Spikeler",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/673.png",
        linkId: 87561,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Psychic, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Religion],
    }, {
        hebrewName: "ציזומי",
        englishName: "Cheezumi",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/674.png",
        linkId: 87562,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Electricity, PokemonType.Flying, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "מונזומי",
        englishName: "Monezzumi",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/675.png",
        linkId: 87563,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Electricity, PokemonType.Flying, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "ניו קידסצ'אנל",
        englishName: "N Kidschannel",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/676.png",
        linkId: 87564,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Earth, PokemonType.Ghost, PokemonType.Science],
    }, {
        hebrewName: "פריביוס קידסצ'אנל",
        englishName: "P Kidschannel",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/677.png",
        linkId: 87565,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Earth, PokemonType.Ghost, PokemonType.Science],
    }, {
        hebrewName: "פייטינג לאמה",
        englishName: "Fighting Llama",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/678.png",
        linkId: 87566,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Flying, PokemonType.Psychic, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Bug, PokemonType.Rock, PokemonType.Dark],
    }, {
        hebrewName: "אבולהלה",
        englishName: "Abulele",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/679.png",
        linkId: 87567,
        majorWeaknesses: [PokemonType.Religion],
        weaknesses: [PokemonType.Fairy],
        resistancess: [PokemonType.Normal, PokemonType.Fighting, PokemonType.Poison, PokemonType.Psychic, PokemonType.Science, PokemonType.Culture],
    }, {
        hebrewName: "ריצ'יליץ'",
        englishName: "Richileech",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/680.png",
        linkId: 87568,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Psychic, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "באטוליץ'",
        englishName: "Batoleech",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/681.png",
        linkId: 87569,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Psychic, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "סאסוליץ'",
        englishName: "Sasoleech",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/682.png",
        linkId: 87570,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Psychic, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "סלייפקה",
        englishName: "Salipaca",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/683.png",
        linkId: 87571,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Ghost, PokemonType.Metal],
    }, {
        hebrewName: "בליצ'י",
        englishName: "Blitsy",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/684.png",
        linkId: 87572,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Electricity, PokemonType.Flying, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "בלץ'",
        englishName: "Bletz",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/685.png",
        linkId: 87573,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Electricity, PokemonType.Flying, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "אייצ'טו-או",
        englishName: "Eychtoo-o",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/686.png",
        linkId: 87574,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Metal],
    }, {
        hebrewName: "תאיטו-או",
        englishName: "Taitoo-o",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/687.png",
        linkId: 87575,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Bug, PokemonType.Fairy, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Metal, PokemonType.Culture],
    }, {
        hebrewName: "היטו-או",
        englishName: "Heatoo-o",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/688.png",
        linkId: 87576,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Fighting, PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Science],
    }, {
        hebrewName: "דדבום",
        englishName: "Deadboom",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/689.png",
        linkId: 87577,
        majorWeaknesses: [PokemonType.Religion],
        weaknesses: [PokemonType.Fairy],
        resistancess: [PokemonType.Normal, PokemonType.Fighting, PokemonType.Poison, PokemonType.Psychic, PokemonType.Science, PokemonType.Culture],
    }, {
        hebrewName: "דדאקס",
        englishName: "Deadex",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/690.png",
        linkId: 87578,
        majorWeaknesses: [PokemonType.Religion],
        weaknesses: [PokemonType.Fairy],
        resistancess: [PokemonType.Normal, PokemonType.Fighting, PokemonType.Poison, PokemonType.Psychic, PokemonType.Science, PokemonType.Culture],
    }, {
        hebrewName: "דדפייט",
        englishName: "Deadfight",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/691.png",
        linkId: 87579,
        majorWeaknesses: [PokemonType.Religion],
        weaknesses: [PokemonType.Fairy],
        resistancess: [PokemonType.Normal, PokemonType.Fighting, PokemonType.Poison, PokemonType.Psychic, PokemonType.Science, PokemonType.Culture],
    }, {
        hebrewName: "טקרס",
        englishName: "Tecars",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/692.png",
        linkId: 87580,
        majorWeaknesses: [PokemonType.Ghost],
        weaknesses: [PokemonType.Bug, PokemonType.Dark, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Poison, PokemonType.Metal, PokemonType.Science, PokemonType.Religion],
    }, {
        hebrewName: "ממודוק",
        englishName: "Memodok",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/693.png",
        linkId: 87581,
        majorWeaknesses: [PokemonType.Ghost],
        weaknesses: [PokemonType.Bug, PokemonType.Dark, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Poison, PokemonType.Metal, PokemonType.Science, PokemonType.Religion],
    }, {
        hebrewName: "אונייריאן",
        englishName: "Oneirian",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/694.png",
        linkId: 87582,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "איריינסס",
        englishName: "Eiriansess",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/695.png",
        linkId: 87583,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "הנאיון",
        englishName: "Heneion",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/696.png",
        linkId: 87584,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "אנאלוסם",
        englishName: "Analosem",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/697.png",
        linkId: 87585,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "דיאנוורקס",
        englishName: "Dineworks",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/698.png",
        linkId: 87586,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "לופיקוטי",
        englishName: "Loophicooty",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/699.png",
        linkId: 87587,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Ghost, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fighting, PokemonType.Psychic, PokemonType.Science],
    }, {
        hebrewName: "מגיקי",
        englishName: "Magiki",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/700.png",
        linkId: 87642,
        majorWeaknesses: [PokemonType.Culture],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Ice, PokemonType.Flying, PokemonType.Psychic, PokemonType.Fairy],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Bug, PokemonType.Rock, PokemonType.Dark],
    }, {
        hebrewName: "מגיקין",
        englishName: "Magikin",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/701.png",
        linkId: 87643,
        majorWeaknesses: [PokemonType.Culture],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Ice, PokemonType.Flying, PokemonType.Psychic, PokemonType.Fairy],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Bug, PokemonType.Rock, PokemonType.Dark],
    }, {
        hebrewName: "טלי",
        englishName: "Tally",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/702.png",
        linkId: 87644,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Rock, PokemonType.Metal],
        resistancess: [PokemonType.Ice],
    }, {
        hebrewName: "חד שופקרן",
        englishName: "Had Shofkern",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/703.png",
        linkId: 87645,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Rock, PokemonType.Metal],
        resistancess: [PokemonType.Ice],
    }, {
        hebrewName: "ג'קולי",
        englishName: "Jaculy",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/704.png",
        linkId: 87646,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Rock, PokemonType.Metal],
        resistancess: [PokemonType.Ice],
    }, {
        hebrewName: "גרובי",
        englishName: "Groovy",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/705.png",
        linkId: 87647,
        majorWeaknesses: [PokemonType.Ice],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Bug, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Earth, PokemonType.Rock, PokemonType.Religion],
    }, {
        hebrewName: "גרוגוזו",
        englishName: "Gruguzu",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/706.png",
        linkId: 87648,
        majorWeaknesses: [PokemonType.Ice],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Bug, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Earth, PokemonType.Rock, PokemonType.Religion],
    }, {
        hebrewName: "פאנליון",
        englishName: "Funlion",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/707.png",
        linkId: 87649,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "פורענבר",
        englishName: "Furanbear",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/708.png",
        linkId: 87650,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Earth, PokemonType.Rock, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Ice, PokemonType.Bug, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "הוטוליפ",
        englishName: "Hottoleap",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/709.png",
        linkId: 87651,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Earth, PokemonType.Rock, PokemonType.Ghost, PokemonType.Dark, PokemonType.Culture, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Ice, PokemonType.Fighting, PokemonType.Psychic, PokemonType.Metal, PokemonType.Fairy, PokemonType.Science],
    }, {
        hebrewName: "טדובלייז",
        englishName: "Teddoblaze",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/710.png",
        linkId: 87652,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Earth, PokemonType.Rock, PokemonType.Ghost, PokemonType.Dark, PokemonType.Culture, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Ice, PokemonType.Fighting, PokemonType.Psychic, PokemonType.Metal, PokemonType.Fairy, PokemonType.Science],
    }, {
        hebrewName: "ספיקדוט",
        englishName: "Spikdott",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/711.png",
        linkId: 87653,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Dragon, PokemonType.Fairy],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Culture],
    }, {
        hebrewName: "טורנלידוט",
        englishName: "Thornlidot",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/712.png",
        linkId: 87654,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Dragon, PokemonType.Fairy],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Culture],
    }, {
        hebrewName: "אלקטרוהרט",
        englishName: "Electroheart",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/713.png",
        linkId: 87655,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Poison, PokemonType.Earth],
        resistancess: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Flying, PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
    }, {
        hebrewName: "לפסל",
        englishName: "Lepsel",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/714.png",
        linkId: 87656,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Psychic, PokemonType.Bug, PokemonType.Ghost, PokemonType.Dragon, PokemonType.Dark, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Electricity, PokemonType.Fighting, PokemonType.Poison, PokemonType.Earth, PokemonType.Metal, PokemonType.Science, PokemonType.Religion],
    }, {
        hebrewName: "נייפיל",
        englishName: "Knifill",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/715.png",
        linkId: 87657,
        majorWeaknesses: [PokemonType.Fighting],
        weaknesses: [PokemonType.Fire, PokemonType.Earth, PokemonType.Science, PokemonType.Religion],
        resistancess: [PokemonType.Normal, PokemonType.Grass, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Psychic, PokemonType.Rock, PokemonType.Ghost, PokemonType.Dragon, PokemonType.Dark, PokemonType.Metal, PokemonType.Culture],
    }, {
        hebrewName: "קושיס",
        englishName: "Koshis",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/716.png",
        linkId: 87658,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Metal],
        resistancess: [PokemonType.Normal, PokemonType.Fire, PokemonType.Poison, PokemonType.Flying],
    }, {
        hebrewName: "קשלוס",
        englishName: "Kashlos",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/717.png",
        linkId: 87659,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Metal],
        resistancess: [PokemonType.Normal, PokemonType.Fire, PokemonType.Poison, PokemonType.Flying],
    }, {
        hebrewName: "קושי מעיין",
        englishName: "Koshi Maayan",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/718.png",
        linkId: 87660,
        majorWeaknesses: [PokemonType.Grass],
        weaknesses: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Earth],
        resistancess: [PokemonType.Normal, PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying],
    }, {
        hebrewName: "חמורוחני",
        englishName: "Hamoruhani",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/719.png",
        linkId: 87661,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Science],
        resistancess: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark],
    }, {
        hebrewName: "מפתחון",
        englishName: "Maftehon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/720.png",
        linkId: 87662,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Metal],
    }, {
        hebrewName: "עפיפון",
        englishName: "Afifon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/721.png",
        linkId: 87663,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Grass, PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Flying, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "סטאלמט",
        englishName: "Stalmet",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/722.png",
        linkId: 87664,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Science],
        resistancess: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark],
    }, {
        hebrewName: "סטראקינג",
        englishName: "Straking",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/723.png",
        linkId: 87665,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Bug, PokemonType.Dragon, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Science],
    }, {
        hebrewName: "קונגסטר",
        englishName: "Kongster",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/724.png",
        linkId: 87666,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fighting, PokemonType.Flying, PokemonType.Psychic, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Bug, PokemonType.Rock, PokemonType.Ghost, PokemonType.Dark],
    }, {
        hebrewName: "קואללון",
        englishName: "Kualalun",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/725.png",
        linkId: 87667,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fighting],
        resistancess: [PokemonType.Ghost],
    }, {
        hebrewName: "חנונשוף",
        englishName: "Hnunshoof",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/726.png",
        linkId: 87668,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Ice, PokemonType.Rock],
        resistancess: [PokemonType.Grass, PokemonType.Earth, PokemonType.Bug, PokemonType.Ghost],
    }, {
        hebrewName: "קוסמושוף",
        englishName: "Kosmoshoof",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/727.png",
        linkId: 87669,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Psychic, PokemonType.Rock, PokemonType.Ghost, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Earth, PokemonType.Bug, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "ינשומורדור",
        englishName: "Yanshumordor",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/728.png",
        linkId: 87670,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Ice, PokemonType.Rock, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
    }, {
        hebrewName: "עקרבי",
        englishName: "Akravi",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/729.png",
        linkId: 87671,
        majorWeaknesses: [PokemonType.Culture],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Ice, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Fairy],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Rock, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "טנקרבי",
        englishName: "Tankravi",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/730.png",
        linkId: 87672,
        majorWeaknesses: [PokemonType.Culture],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Ice, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Fairy],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Rock, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "פיגראס",
        englishName: "Figrass",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/731.png",
        linkId: 87673,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "פיגרוט",
        englishName: "Figroot",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/732.png",
        linkId: 87674,
        majorWeaknesses: [PokemonType.Bug],
        weaknesses: [PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Dragon, PokemonType.Dark],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
    }, {
        hebrewName: "חלקיק",
        englishName: "Halakik",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/733.png",
        linkId: 87708,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug],
        resistancess: [PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Earth, PokemonType.Religion],
    }, {
        hebrewName: "הידרוקינון",
        englishName: "Hydrocinnon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/734.png",
        linkId: 87709,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Psychic, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "סטינק בומב",
        englishName: "Stink Bomb",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/735.png",
        linkId: 87710,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Psychic, PokemonType.Rock, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "תיקן",
        englishName: "Tikan",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/736.png",
        linkId: 87711,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Bug, PokemonType.Rock, PokemonType.Fairy, PokemonType.Religion],
        resistancess: [PokemonType.Grass, PokemonType.Earth, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Culture],
    }, {
        hebrewName: "תיקתיקן",
        englishName: "Tiktikan",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2020/06/737.png",
        linkId: 87712,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Bug, PokemonType.Rock, PokemonType.Fairy, PokemonType.Religion],
        resistancess: [PokemonType.Grass, PokemonType.Earth, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Culture],
    }, {
        hebrewName: "וירוס",
        englishName: "Virus",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/738.png",
        linkId: 87713,
        majorWeaknesses: [PokemonType.Earth, PokemonType.Science],
        weaknesses: [PokemonType.Psychic],
        resistancess: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug, PokemonType.Metal, PokemonType.Fairy, PokemonType.Religion],
    }, {
        hebrewName: "מלחלזון",
        englishName: "Melahilazon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/739.png",
        linkId: 87714,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Bug, PokemonType.Fairy, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Metal, PokemonType.Culture],
    }, {
        hebrewName: "רותמנון",
        englishName: "Rotamnoon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/740.png",
        linkId: 87715,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Earth, PokemonType.Rock, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Ice, PokemonType.Bug, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "באבלי",
        englishName: "Bubbly",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/741.png",
        linkId: 87716,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Metal],
    }, {
        hebrewName: "באבלוז",
        englishName: "Bubblooz",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/742.png",
        linkId: 87717,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Rock, PokemonType.Metal],
        resistancess: [PokemonType.Ice],
    }, {
        hebrewName: "באבל",
        englishName: "Bubble",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/743.png",
        linkId: 87718,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Normal, PokemonType.Water, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Psychic, PokemonType.Bug, PokemonType.Rock, PokemonType.Dragon, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "זיגדרה",
        englishName: "Zigdra",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/744.png",
        linkId: 87719,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Earth, PokemonType.Psychic, PokemonType.Dragon, PokemonType.Science],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "זוהאם",
        englishName: "Zoham",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/745.png",
        linkId: 87720,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Earth, PokemonType.Psychic, PokemonType.Dragon, PokemonType.Science],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Culture, PokemonType.Religion],
    }, {
        hebrewName: "פיקסייט",
        englishName: "Pixite",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/746.png",
        linkId: 87721,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Ghost, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fighting, PokemonType.Psychic, PokemonType.Science],
    }, {
        hebrewName: "קריסטייט",
        englishName: "Crystite",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/747.png",
        linkId: 87722,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Poison, PokemonType.Ghost, PokemonType.Metal, PokemonType.Religion],
        resistancess: [PokemonType.Fighting, PokemonType.Psychic, PokemonType.Dragon, PokemonType.Science],
    }, {
        hebrewName: "נובורוג",
        englishName: "Noboroog",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/748.png",
        linkId: 87723,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Flying, PokemonType.Bug, PokemonType.Rock, PokemonType.Ghost, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Psychic, PokemonType.Science, PokemonType.Culture],
    }, {
        hebrewName: "פילוסוף",
        englishName: "Philosof",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/749.png",
        linkId: 87724,
        majorWeaknesses: [PokemonType.Metal],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Earth],
        resistancess: [PokemonType.Normal, PokemonType.Fire, PokemonType.Flying, PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Science],
    }, {
        hebrewName: "אנון עברי",
        englishName: "Hebrew Unown",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/750.png",
        linkId: 87726,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
    }, {
        hebrewName: "אנונימוס",
        englishName: "Unownymous",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/751.png",
        linkId: 87727,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Science],
        resistancess: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark],
    }, {
        hebrewName: "סטאריו ישראלי",
        englishName: "IL Staryu",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/752.png",
        linkId: 87728,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Normal, PokemonType.Water, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Psychic, PokemonType.Bug, PokemonType.Rock, PokemonType.Dragon, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "סטארמי ישראלי",
        englishName: "IL Starmie",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/753.png",
        linkId: 87729,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
        resistancess: [PokemonType.Normal, PokemonType.Water, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Psychic, PokemonType.Bug, PokemonType.Rock, PokemonType.Dragon, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "ליטוויק ישראלי",
        englishName: "IL Litwick",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/754.png",
        linkId: 87730,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Earth, PokemonType.Rock, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Ice, PokemonType.Bug, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "לאמפנט ישראלי",
        englishName: "IL Lampent",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/755.png",
        linkId: 87731,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Electricity, PokemonType.Poison, PokemonType.Earth, PokemonType.Rock, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Ice, PokemonType.Psychic, PokemonType.Bug, PokemonType.Ghost, PokemonType.Dark, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "שאנדלור ישראלי",
        englishName: "IL Chandelure",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/756.png",
        linkId: 87732,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Electricity, PokemonType.Poison, PokemonType.Earth, PokemonType.Rock, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Ice, PokemonType.Psychic, PokemonType.Bug, PokemonType.Ghost, PokemonType.Dark, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "קאבוטו ישראלי",
        englishName: "IL Kabuto",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/757.png",
        linkId: 87733,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Flying, PokemonType.Rock],
        resistancess: [PokemonType.Water, PokemonType.Ice, PokemonType.Fighting, PokemonType.Earth, PokemonType.Metal, PokemonType.Culture],
    }, {
        hebrewName: "קאבוטופס ישראלי",
        englishName: "IL Kabutops",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/758.png",
        linkId: 87734,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Flying, PokemonType.Rock],
        resistancess: [PokemonType.Water, PokemonType.Ice, PokemonType.Fighting, PokemonType.Earth, PokemonType.Metal, PokemonType.Culture],
    }, {
        hebrewName: "אירודקטייל ישראלי",
        englishName: "IL Aerodactyl",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/759.png",
        linkId: 87735,
        majorWeaknesses: [PokemonType.Water, PokemonType.Earth],
        weaknesses: [PokemonType.Fighting, PokemonType.Rock, PokemonType.Culture],
        resistancess: [PokemonType.Normal, PokemonType.Fire, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug, PokemonType.Fairy],
    }, {
        hebrewName: "גלוארק",
        englishName: "Gloark",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/760.png",
        linkId: 87736,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Ghost, PokemonType.Dark],
        resistancess: [PokemonType.Normal, PokemonType.Electricity, PokemonType.Fighting, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug, PokemonType.Metal],
    }, {
        hebrewName: "פלאפלולי",
        englishName: "Falafeluli",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/761.png",
        linkId: 87737,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
    }, {
        hebrewName: "שווארמגדון",
        englishName: "Shwarmagedon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/762.png",
        linkId: 87738,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Rock, PokemonType.Dragon, PokemonType.Dark, PokemonType.Culture, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Ice, PokemonType.Fighting, PokemonType.Metal, PokemonType.Fairy, PokemonType.Science],
    }, {
        hebrewName: "עיניון",
        englishName: "Inyon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/763.png",
        linkId: 87739,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fighting],
        resistancess: [PokemonType.Ghost],
    }, {
        hebrewName: "תוניון",
        englishName: "Twonyon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/764.png",
        linkId: 87740,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Ice, PokemonType.Rock],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Bug],
    }, {
        hebrewName: "תריליון",
        englishName: "Threelyon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/765.png",
        linkId: 87741,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Ice, PokemonType.Rock],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Bug],
    }, {
        hebrewName: "רוקטון",
        englishName: "Rockton",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/766.png",
        linkId: 87742,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Metal],
        resistancess: [PokemonType.Normal, PokemonType.Fire, PokemonType.Poison, PokemonType.Flying],
    }, {
        hebrewName: "קרולסטון",
        englishName: "Crollstone",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/767.png",
        linkId: 87743,
        majorWeaknesses: [PokemonType.Fighting, PokemonType.Earth],
        weaknesses: [PokemonType.Water, PokemonType.Science],
        resistancess: [PokemonType.Normal, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Psychic, PokemonType.Bug, PokemonType.Rock, PokemonType.Dragon, PokemonType.Fairy],
    }, {
        hebrewName: "וולי",
        englishName: "Wooly",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/768.png",
        linkId: 87744,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Rock, PokemonType.Metal],
        resistancess: [PokemonType.Ice],
    }, {
        hebrewName: "זעממו",
        englishName: "Za'amamu",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/769.png",
        linkId: 87745,
        majorWeaknesses: [PokemonType.Fighting, PokemonType.Metal],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Earth, PokemonType.Rock],
        resistancess: [PokemonType.Normal, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying],
    }, {
        hebrewName: "כרישארק",
        englishName: "Karishark",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/770.png",
        linkId: 87746,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Metal],
    }, {
        hebrewName: "קראלודון",
        englishName: "Kralodon",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/771.png",
        linkId: 87747,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Dragon, PokemonType.Fairy],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Metal, PokemonType.Culture],
    }, {
        hebrewName: "מדוזה",
        englishName: "Medusa",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/772.png",
        linkId: 87748,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Psychic, PokemonType.Science],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Fairy, PokemonType.Religion],
    }, {
        hebrewName: "אלישע",
        englishName: "Elisha",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/773.png",
        linkId: 87749,
        majorWeaknesses: [PokemonType.Electricity, PokemonType.Grass],
        weaknesses: [PokemonType.Poison, PokemonType.Science],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Metal],
    }, {
        hebrewName: "אליהו",
        englishName: "Eliyahoo",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/774.png",
        linkId: 87750,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Electricity, PokemonType.Poison, PokemonType.Earth, PokemonType.Rock, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Ice, PokemonType.Psychic, PokemonType.Bug, PokemonType.Ghost, PokemonType.Dark, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "קספירל",
        englishName: "Kespiral",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/775.png",
        linkId: 87751,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Poison, PokemonType.Metal, PokemonType.Fairy],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Fighting, PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Science, PokemonType.Culture],
    }, {
        hebrewName: "הוסו",
        englishName: "Hoso",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/776.png",
        linkId: 87752,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ice, PokemonType.Psychic, PokemonType.Rock, PokemonType.Ghost, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Grass, PokemonType.Fighting, PokemonType.Poison, PokemonType.Earth, PokemonType.Bug, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "מומקרן",
        englishName: "Mumkern",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/777.png",
        linkId: 87753,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Religion],
        resistancess: [PokemonType.Normal, PokemonType.Fighting, PokemonType.Psychic, PokemonType.Bug],
    }, {
        hebrewName: "נגקוסל",
        englishName: "Negakosel",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/778.png",
        linkId: 87754,
        majorWeaknesses: [PokemonType.Fairy],
        weaknesses: [PokemonType.Ice, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dragon],
        resistancess: [PokemonType.Fire, PokemonType.Water, PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "פיקאצ'ו מעבדה",
        englishName: "Lab Pikachu",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/779.png",
        linkId: 87755,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Psychic, PokemonType.Ghost, PokemonType.Fairy, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Flying, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "שרדיקאצ'ו",
        englishName: "Shradikachu",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/780.png",
        linkId: 87756,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Ghost, PokemonType.Dark],
        resistancess: [PokemonType.Normal, PokemonType.Electricity, PokemonType.Fighting, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug, PokemonType.Metal],
    }, {
        hebrewName: "ראידינגר",
        englishName: "Raidinger",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/781.png",
        linkId: 87757,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Earth, PokemonType.Psychic, PokemonType.Fairy, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Bug, PokemonType.Rock, PokemonType.Dark, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "ציזומי איקס 49",
        englishName: "Cheezumi X49",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/782.png",
        linkId: 87758,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Ghost, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Normal, PokemonType.Electricity, PokemonType.Grass, PokemonType.Ice, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug, PokemonType.Rock, PokemonType.Dragon, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "סנדספייק",
        englishName: "Sandspike",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/783.png",
        linkId: 87759,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Ice, PokemonType.Metal, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Fighting, PokemonType.Bug, PokemonType.Rock, PokemonType.Dragon, PokemonType.Dark, PokemonType.Science],
    }, {
        hebrewName: "ניין קאט",
        englishName: "Nine Cat",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/784.png",
        linkId: 87760,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fighting],
        resistancess: [PokemonType.Ghost],
    }, {
        hebrewName: "ניין בוי",
        englishName: "Nine Boy",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/785.png",
        linkId: 87761,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Poison, PokemonType.Metal],
        resistancess: [PokemonType.Fighting, PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Science],
    }, {
        hebrewName: "ניין צ'שייר",
        englishName: "Nine Cheshire",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/786.png",
        linkId: 87725,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Ghost, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Normal, PokemonType.Fighting, PokemonType.Poison, PokemonType.Bug, PokemonType.Science],
    }, {
        hebrewName: "ניין צל",
        englishName: "Nine Tzel",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/787.png",
        linkId: 87820,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fighting, PokemonType.Bug, PokemonType.Fairy, PokemonType.Religion],
        resistancess: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Culture],
    }, {
        hebrewName: "ניין גרדיאן",
        englishName: "Nine Guardian",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/788.png",
        linkId: 87821,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Science],
        resistancess: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark],
    }, {
        hebrewName: "ניין הילה",
        englishName: "Nine Hila",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/789.png",
        linkId: 87822,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Ghost, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fighting, PokemonType.Psychic, PokemonType.Science],
    }, {
        hebrewName: "ניין בוט",
        englishName: "Nine Boot",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/790.png",
        linkId: 87823,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Flying, PokemonType.Psychic, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Bug, PokemonType.Rock, PokemonType.Dark],
    }, {
        hebrewName: "ניין מצפון",
        englishName: "Nine Mazpun",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/791.png",
        linkId: 87824,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
    }, {
        hebrewName: "ניין שן",
        englishName: "Nine Shen",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/792.png",
        linkId: 87825,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Rock, PokemonType.Metal],
        resistancess: [PokemonType.Ice],
    }, {
        hebrewName: "ניין ספינקס",
        englishName: "Nine Sphinx",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/793.png",
        linkId: 87826,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Earth, PokemonType.Rock, PokemonType.Culture],
        resistancess: [PokemonType.Fire, PokemonType.Grass, PokemonType.Ice, PokemonType.Bug, PokemonType.Metal, PokemonType.Fairy],
    }, {
        hebrewName: "רוק",
        englishName: "Rock",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/794.png",
        linkId: 87827,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Fighting, PokemonType.Earth, PokemonType.Psychic, PokemonType.Metal, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Normal, PokemonType.Fire, PokemonType.Poison, PokemonType.Bug, PokemonType.Rock, PokemonType.Dark],
    }, {
        hebrewName: "קפטן רוק",
        englishName: "Captain Rock",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/795.png",
        linkId: 87828,
        majorWeaknesses: [PokemonType.Culture],
        weaknesses: [PokemonType.Water, PokemonType.Grass, PokemonType.Ice, PokemonType.Flying, PokemonType.Psychic, PokemonType.Fairy],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Bug, PokemonType.Rock, PokemonType.Dark],
    }, {
        hebrewName: "קינג רוק",
        englishName: "King Rock",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/796.png",
        linkId: 87829,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science, PokemonType.Culture],
        resistancess: [PokemonType.Normal, PokemonType.Grass, PokemonType.Ice, PokemonType.Poison, PokemonType.Bug, PokemonType.Rock, PokemonType.Dragon, PokemonType.Dark, PokemonType.Metal],
    }, {
        hebrewName: "טרידאדס",
        englishName: "Tridads",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/797.png",
        linkId: 87830,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Bug, PokemonType.Religion],
        resistancess: [PokemonType.Fighting, PokemonType.Psychic],
    }, {
        hebrewName: "קיוואק",
        englishName: "Cuewack",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/798.png",
        linkId: 87831,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Fairy, PokemonType.Culture],
        resistancess: [PokemonType.Electricity, PokemonType.Poison, PokemonType.Metal, PokemonType.Religion],
    }, {
        hebrewName: "גרוביס",
        englishName: "Garubies",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/799.png",
        linkId: 87832,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Electricity, PokemonType.Grass, PokemonType.Poison, PokemonType.Science],
        resistancess: [PokemonType.Psychic, PokemonType.Ghost, PokemonType.Dark, PokemonType.Culture],
    }, {
        hebrewName: "קוביאיי",
        englishName: "Cobieye",
        imageId: "https://www.pocketmonsters.co.il/wp-content/uploads/2010/06/800.png",
        linkId: 87833,
        majorWeaknesses: [],
        weaknesses: [PokemonType.Bug, PokemonType.Dragon, PokemonType.Dark, PokemonType.Religion],
        resistancess: [PokemonType.Fire, PokemonType.Fighting, PokemonType.Earth, PokemonType.Science],
    },];

export default data;
